version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://postgresql-db:5432/bliushtein_yp_sprint5_db
      SPRING_R2DBC_USERNAME: bliushtein_yp_sprint5
      SPRING_R2DBC_PASSWORD: 12345
  postgresql-db:
    image: "postgres:17"
    environment:
      POSTGRES_DB: bliushtein_yp_sprint5_db
      POSTGRES_USER: bliushtein_yp_sprint5
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
