openapi: 3.0.3
info:
  title: API для получения текущего баланса и выполнения платежей
  version: 1.0.0
servers:
- url: /
paths:
  /balance:
    get:
      operationId: getBalance
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response"
              examples:
                $ref: "#/components/examples/success_response"
          description: Успешный ответ
        "5XX":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response"
              examples:
                $ref: "#/components/examples/error_response"
          description: Внутренняя ошибка сервиса
      summary: Получить текущий баланс
      x-accepts:
      - application/json
    put:
      operationId: pay
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/pay_request"
        description: Данные для выполнения платежа
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response"
              examples:
                $ref: "#/components/examples/success_response"
          description: Платеж выполнен успешно
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response"
              examples:
                $ref: "#/components/examples/error_response"
          description: Недостаточно средств для совершения платежа
        "5XX":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response"
              examples:
                $ref: "#/components/examples/error_response"
          description: Внутренняя ошибка сервиса
      summary: оплатить заказ
      x-content-type: application/json
      x-accepts:
      - application/json
components:
  schemas:
    response:
      type: object
      properties:
        type:
          type: string
          enum:
            - success
            - error
        balance:
          description: текущий баланс
          exclusiveMinimum: false
          minimum: 0
          nullable: false
          type: integer
        error:
          nullable: false
          type: string
      required:
        - type
#      discriminator:
#        propertyName: type
#        mapping:
#          success: '#/components/schemas/ok_response'
#          error: '#/components/schemas/nok_response'
#    ok_response:
#      allOf:
#        - $ref: '#/components/schemas/response'
#        - type: object
#          required:
#            - balance
#    nok_response:
#      allOf:
#        - $ref: '#/components/schemas/response'
#        - type: object
#          required:
#            - error
    pay_request:
      properties:
        price:
          exclusiveMinimum: true
          minimum: 0
          type: integer
      type: object
  examples:
    success_response:
      summary: успешный ответ
      value:
        type: success
        balance: 50
    error_response:
      summary: ошибка
      value:
        type: error
        error: сообщение об ошибке