management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState
          show-details: always
spring:
  application:
    name: bliushtein_sprint5
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/bliushtein_yp_sprint5_db
    username: bliushtein_yp_sprint5
    password: 12345
  sql:
    init:
      mode: always
      schema-locations: classpath:/db/schema.sql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update
logging:
  level:
    ru.yandex.practicum.bliushtein.spr5: "debug"
  docker:
    compose:
      enabled: true
      file: docker-compose-for-bootRun.yml
      start:
        log-level: debug
