management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState
          show-details: always
spring:
  application:
    name: bliushtein_sprint5
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: create
logging:
  level:
    ru.yandex.practicum.bliushtein.spr5: "debug"
  docker:
    compose:
      enabled: true
      file: docker-compose-for-bootRun.yml
      start:
        log-level: debug
